# -*- coding: utf-8 -*-
"""Adaptive Model Mapping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LZ0RddptBKdf068ddd8TOiz_TKuwxqwh
"""

"""The whole idea in three sentences:

We want A and B equally attractive.
A third option C (the decoy) is added at every position on a 10x10 grid of the attribute
space, and each model predicts how the decoy shifts choices between A and B.
Plotting the shift from the decoy at every grid position gives each model's predicted
"decoy-influence map"

Model forms are taken from the Seminar 2 notebook, with three adaptations:
1. The seminar models are about gambles with probability. Plans have no probability, so EV becomes an equally-weighted sum
   of the two attributes (the weight plays the role probability played).

2. The seminar functions use only one list of values. Options here have two
   attributes, so each function has to be applied to each attribute.

3. Models output values, but we need probabilities of who will choose an option, meaning we use the softmax rule. (found with a google search. Is there a better option?)
   And prospect theory needs a reference point: a reference point of zero makes PT identical to EU, so the reference is the
   mean of the options on the table.
"""

import numpy as np
import matplotlib.pyplot as plt

# --- THE CHOICE SET ---
# Change these coordinates to move the 'target' options.
# Right now they are symmetric [Economy, Quality] pairs.
A, B = np.array([0.7, 0.3]), np.array([0.3, 0.7])

# --- MATHEMATICAL MODELS ---
# These functions define how each model 'perceives' the value of the options.
# Prospect Theory (pt) is defined as a function; the others are simple lambdas.
def pt(X, alpha=0.88, lam=2.25):
    z = X - X.mean(0)
    return np.where(z >= 0, np.abs(z)**alpha, -lam * np.abs(z)**alpha)

MODELS = {
    "EV": lambda X: X,
    "EU": lambda X: X**0.88,
    "Prospect theory": pt,
    "Range norm.": lambda X: X / (X.max(0) - X.min(0)),
    "Divisive norm.": lambda X: X / X.mean(0),
    "Recurrent norm.": lambda X: X / (X + X.mean(0)),
    "Adaptive gain": lambda X: 1 / (1 + np.exp(-8 * (X - X.mean(0))))
}

# CHOICE PROBABILITY (SOFTMAX)
# Turning 'values' into a probability of picking A vs B.
# Beta controls 'choice precision' (higher beta = more rational/extreme).
def share_of_A(X, model, beta=8):
    v = model(X).mean(1)
    p = np.exp(beta * (v - v.max()))
    return p[0] / (p[0] + p[1])

# GRID GENERATION
# We sweep the space with a decoy and record the 'shift' it causes.
def get_map(model, grid):
    base = share_of_A(np.stack([A, B]), model)
    return np.array([[(share_of_A(np.stack([A, B, [e, q]]), model) - base) * 100
                      for e in grid] for q in grid])


# Calculate the influence maps for every model defined above.
grid = np.linspace(0.05, 0.95, 10)
maps = {n: get_map(m, grid) for n, m in MODELS.items()}


# Generate the heatmaps. Red = shift toward A, Blue = shift toward B.
vmax = max(abs(m).max() for m in maps.values())
fig, axes = plt.subplots(2, 4, figsize=(14, 7), layout='constrained')

for ax, (name, m) in zip(axes.flatten(), maps.items()):
    im = ax.imshow(m, origin="lower", cmap="RdBu_r", vmin=-vmax, vmax=vmax, extent=[0, 1, 0, 1])
    ax.plot([0, 1], [1, 0], ":k", alpha=0.3) # The indifference line
    for p, l, o in [(A, "A", [.04, -.08]), (B, "B", [.04, .04])]:
        ax.plot(*p, "ko"); ax.text(p[0]+o[0], p[1]+o[1], l, weight="bold")
    ax.set_title(name)

axes[1, 3].axis("off")
fig.supxlabel("decoy cheapness"); fig.supylabel("decoy quality")
fig.suptitle("Predicted decoy-influence maps by model")
fig.colorbar(im, ax=axes, shrink=0.8, label="shift toward A (pp)")

plt.savefig("decoy_maps.png")
plt.show()