{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyN3PUJBiVxZhel+sr9l57pn"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "lEn03TO5ZcNa"
      },
      "outputs": [],
      "source": [
        "\"\"\"Stress-test of the dominating-decoy critique (Dr. Dumbalska).\n",
        "\n",
        "Claim under test: trials where the decoy DOMINATES a target (cells d1, d2)\n",
        "carry no useful information for discriminating the theories, because\n",
        "choosing a dominating option is what every theory predicts.\n",
        "\n",
        "Three measurements:\n",
        "1. Where the design's discriminating power lives, cell by cell. Total\n",
        "   pairwise KL between calibrated theories at each menu, split into the\n",
        "   FULL trinary distribution vs the CONDITIONAL A-vs-B split (the\n",
        "   mechanism-relevant part her paradigm uses).\n",
        "2. Recovery re-run, regime DROP: the design without d1/d2 (28 trials pp).\n",
        "3. Recovery re-run, regime COND: full design, but at d1/d2 the analysis\n",
        "   uses only the conditional A-vs-B information (decoy-picks discarded).\n",
        "Baseline for comparison: full-design recovery = 15/18 (fit_recover.py).\n",
        "\n",
        "Run: python dominance_stress_test.py\n",
        "\"\"\"\n",
        "\n",
        "import csv\n",
        "import itertools\n",
        "\n",
        "import numpy as np\n",
        "from scipy.optimize import minimize\n",
        "\n",
        "# --- setup (identical machinery to fit_recover.py) ------------------------\n",
        "BIG = (\"O2\", \"Vodafone\", \"Three\", \"EE\", \"Sky\")\n",
        "rows = list(csv.DictReader(open(\"../data/market_deals.csv\")))\n",
        "deals = [(float(r[\"data_gb\"]), float(r[\"price_gbp_month\"]),\n",
        "          r[\"provider\"].startswith(BIG) and \"mobiles\" not in r[\"provider\"]\n",
        "          and \"Fonehouse\" not in r[\"provider\"])\n",
        "         for r in rows if r[\"unlimited\"] == \"0\"]\n",
        "gb = np.array([d[0] for d in deals]); price = np.array([d[1] for d in deals])\n",
        "val = ~np.array([d[2] for d in deals])\n",
        "b, a = np.polyfit(np.log2(gb[val]), price[val], 1)\n",
        "res = price - (a + b * np.log2(gb)); r_lo, r_hi = np.percentile(res, [5, 95])\n",
        "GB_LO, GB_HI = 25, 310\n",
        "P_LO = a + b * np.log2(GB_LO) + r_lo; P_HI = a + b * np.log2(GB_HI) + r_hi\n",
        "plan = lambda g, p: np.array([(P_HI - p) / (P_HI - P_LO),\n",
        "                              np.log2(g / GB_LO) / np.log2(GB_HI / GB_LO)])\n",
        "A, B = plan(100, 17.0), plan(200, 20.0)\n",
        "CELLS = {\"d1\": plan(100, 12.0), \"d2\": plan(130, 14.0), \"d3\": plan(160, 24.5),\n",
        "         \"d4\": plan(130, 22.5), \"d5\": plan(210, 26.5), \"d6\": plan(30, 18.0)}\n",
        "DOM = {\"d1\", \"d2\"}                       # cells whose decoy dominates A\n",
        "\n",
        "def pt(X, al=0.88, lam=2.25):\n",
        "    z = X - X.mean(0)\n",
        "    return np.where(z >= 0, np.abs(z)**al, -lam * np.abs(z)**al)\n",
        "MODELS = {\n",
        "    \"EV\": lambda X: X, \"PT\": pt,\n",
        "    \"Range\": lambda X: X / (X.max(0) - X.min(0)),\n",
        "    \"Divisive\": lambda X: X / X.mean(0),\n",
        "    \"Recurrent\": lambda X: X / (X + X.mean(0)),\n",
        "    \"AdaptGain\": lambda X: 1 / (1 + np.exp(-8 * (X - X.mean(0)))),\n",
        "}\n",
        "def probs(X, m, w, beta):\n",
        "    v = w * m(X)[:, 0] + (1 - w) * m(X)[:, 1]\n",
        "    p = np.exp(beta * (v - v.max())); return p / p.sum()\n",
        "def fair_w(m):\n",
        "    lo, hi = 0.02, 0.98\n",
        "    for _ in range(60):\n",
        "        mid = (lo + hi) / 2\n",
        "        if probs(np.stack([A, B]), m, mid, 8.0)[0] < 0.5: lo = mid\n",
        "        else: hi = mid\n",
        "    return (lo + hi) / 2\n",
        "W = {n: fair_w(m) for n, m in MODELS.items()}\n",
        "NAMES = list(MODELS)\n",
        "\n",
        "MENUS = {\"baseline\": (np.stack([A, B]), 8 * 18)}\n",
        "for k, d in CELLS.items():\n",
        "    MENUS[k] = (np.stack([A, B, d]), 5 * 18)\n",
        "\n",
        "# --- 1. per-cell discrimination, full vs conditional ----------------------\n",
        "def kl(p, q): return float(np.sum(p * np.log(p / np.maximum(q, 1e-12))))\n",
        "print(\"per-cell discriminating power (sum of pairwise KL over all 15 model\")\n",
        "print(\"pairs, weighted by trial count; 'conditional' = A-vs-B split only):\")\n",
        "print(f\"{'cell':9s} {'full':>8s} {'conditional':>12s} {'share in P(decoy)':>18s}\")\n",
        "tot_full = tot_cond = 0.0\n",
        "for k, (X, n) in MENUS.items():\n",
        "    P = {m: probs(X, MODELS[m], W[m], 8.0) for m in NAMES}\n",
        "    f = c = 0.0\n",
        "    for i, j in itertools.combinations(NAMES, 2):\n",
        "        f += n * (kl(P[i], P[j]) + kl(P[j], P[i])) / 2\n",
        "        pi = P[i][:2] / P[i][:2].sum(); pj = P[j][:2] / P[j][:2].sum()\n",
        "        c += n * (kl(pi, pj) + kl(pj, pi)) / 2\n",
        "    tot_full += f; tot_cond += c\n",
        "    tag = \" <-- dominating\" if k in DOM else \"\"\n",
        "    print(f\"{k:9s} {f:8.1f} {c:12.1f} {100*(f-c)/max(f,1e-9):17.0f}%{tag}\")\n",
        "print(f\"{'TOTAL':9s} {tot_full:8.1f} {tot_cond:12.1f}\")\n",
        "dom_share = sum(1 for _ in ())  # placeholder to keep flow clear\n",
        "\n",
        "# --- 2 & 3. recovery under three regimes ----------------------------------\n",
        "def make_trials(drop_dom):\n",
        "    T = []\n",
        "    for k, (X, n) in MENUS.items():\n",
        "        if drop_dom and k in DOM: continue\n",
        "        per = n // 18\n",
        "        T += [(k, X)] * per\n",
        "    return T\n",
        "\n",
        "def simulate(model, w, rng, trials):\n",
        "    return [(k, X, rng.choice(len(probs(X, model, w, 8.0)),\n",
        "                              p=probs(X, model, w, 8.0)))\n",
        "            for _ in range(18) for k, X in trials]\n",
        "\n",
        "def neg_ll(prm, data, m, conditional):\n",
        "    w, beta = prm\n",
        "    if not (0.001 < w < 0.999 and 0 < beta < 100): return 1e9\n",
        "    cache = {}\n",
        "    ll = 0.0\n",
        "    for k, X, c in data:\n",
        "        if k not in cache: cache[k] = probs(X, m, w, beta)\n",
        "        p = cache[k]\n",
        "        if conditional and k in DOM:\n",
        "            if c == 2: continue                      # decoy pick: discarded\n",
        "            ll += np.log(max(p[c] / (p[0] + p[1]), 1e-12))\n",
        "        else:\n",
        "            ll += np.log(max(p[c], 1e-12))\n",
        "    return -ll\n",
        "\n",
        "def recover(regime):\n",
        "    drop = regime == \"DROP\"; cond = regime == \"COND\"\n",
        "    trials = make_trials(drop)\n",
        "    correct = 0; lines = []\n",
        "    for gi, g in enumerate(NAMES):\n",
        "        for rep in range(3):\n",
        "            rng = np.random.default_rng(1000 + 17 * gi + rep)  # same seeds\n",
        "            data = simulate(MODELS[g], W[g], rng, trials)\n",
        "            lls = []\n",
        "            for m in NAMES:\n",
        "                best = min((minimize(neg_ll, x0, args=(data, MODELS[m], cond),\n",
        "                                     method=\"L-BFGS-B\",\n",
        "                                     bounds=[(0.02, 0.98), (0.1, 60)]).fun\n",
        "                            for x0 in [(0.3, 4), (0.5, 8), (0.7, 4), (0.6, 16)]))\n",
        "                lls.append(-best)\n",
        "            order = np.argsort(lls)[::-1]\n",
        "            ok = order[0] == gi\n",
        "            correct += ok\n",
        "            if not ok:\n",
        "                lines.append(f\"    miss: {g} -> {NAMES[order[0]]} \"\n",
        "                             f\"(margin {lls[order[0]] - lls[order[1]]:.1f})\")\n",
        "    print(f\"regime {regime:5s}: {correct}/18 recovered\")\n",
        "    for l in lines: print(l)\n",
        "\n",
        "print(\"\\nrecovery (baseline FULL regime was 15/18):\")\n",
        "recover(\"DROP\")\n",
        "recover(\"COND\")"
      ]
    }
  ]
}